title: Hasanagha Azad
author: Hasanagha Azad
email: hasanaghaazad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Its my firs experience in Github Pages. I plan to use this tool as my online resume

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # HasanaghaAzad

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
